explaining merging and error situation
ESSS/conda-devenv pull request #115
Opened 2020-09-06 21:35 UTC by majidaldo

#112

2020-09-08 12:46 UTC, prusse-martin requested changes

2020-09-08 12:46 UTC, prusse-martin commented on docs/usage.rst
> +variables in a file using the appropriate separator for the platform (``:`` on Linux/OSX and ``;`` on Windows).
```suggestion
environment variables with the values found in the ``.devenv.yml`` file, using the appropriate separator for the platform (``:`` on Linux/OSX and ``;`` on Windows).
```

2020-09-08 12:46 UTC, prusse-martin commented on docs/usage.rst
> +variable with the same name in a file.
```suggestion
environment variable with the value from the ``.devenv.yml`` file.
```

2020-09-08 12:46 UTC, prusse-martin commented on docs/usage.rst
> +In other words, an 'overwrite' situation is not allowed between files.
```suggestion
However, the same environment variable defined as a single string (like ``DB_LOCATION`` above) in both files will raise an error
unless it is not allowed to 'pass through' using the ``# [not is_included]`` selector above as an example.
In other words, an 'overwrite' situation is not allowed between files.
```

The syntax `# [some_bool_expr]` have been copied from [conda build and they call it preprocessing selectors](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#preprocessing-selectors) I think we should you the same term. Actually [our docs describe the feature in jinja section](https://conda-devenv.readthedocs.io/en/latest/usage.html#jinja2) but fails to point the origin and I think we should use the same name and add an reference to the conda-build.

2020-09-08 12:49 UTC, prusse-martin commented
I did add a link to conda-build's preprocessing selectors.

2020-09-09 11:23 UTC, nicoddemus approved these changes

2020-09-09 11:23 UTC, nicoddemus commented
Thanks @majidaldo! 

@prusse-martin let's squash merge this. 👍

2020-09-09 12:35 UTC, prusse-martin commented
Ty for the PR @majidaldo.

2020-09-09 12:36 UTC, prusse-martin approved these changes

2020-09-09 12:38 UTC, merged